apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-agent-to-ingest
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: file-agent
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ingest-api
    ports:
    - protocol: TCP
      port: 3000
